uma_arm_dynamics:
  ros__parameters:
    frequency: 1000.0
    m1: 2.9
    m2: 1.9
    l1: 0.9
    l2: 0.5
    b1: 4.9
    b2: 4.9
    g: 9.81
    q0: [1.570796, -0.785398]

gravity_compensation:
  ros__parameters:
    frequency: 1000.0
    m1: 3.0
    m2: 2.0
    l1: 1.0
    l2: 0.6
    b1: 5.0
    b2: 5.0
    g: 9.81
    q0: [0.785398, -0.785398]

dynamics_cancellation:
  ros__parameters:
    frequency: 1000.0
    m1: 3.0
    m2: 2.0
    l1: 1.0
    l2: 0.6
    b1: 5.0
    b2: 5.0
    g: 9.81
    q0: [0.785398, -0.785398]